
tile_size: 32
max_fov: 15
monsters_settings: 
    amount: 50
    z_level: 1
    monsters: [
        {
            actor_settings: {
                sprite_index: 69,
                name: "Yoga Bunny",
                max_health: 1,
                fov_radius: 6,
            },
            behaviour: Random,
            proportion: 50,
        },
        {
            actor_settings: {
                sprite_index: 111,
                name: "Nutritionist",
                max_health: 2,
                fov_radius: 6,
            },
            behaviour: Chasing,
            proportion: 10,
        },
        {
            actor_settings: {
                sprite_index: 79,
                name: "Gym Bro",
                max_health: 4,
                fov_radius: 6,
            },
            behaviour: Chasing,
            proportion: 30,
        },
        {
            actor_settings: {
                sprite_index: 103,
                name: "Supplement Pusher",
                max_health: 3,
                fov_radius: 10,
            },
            behaviour: Chasing,
            proportion: 10,
        },
    ]
map_settings: 
    floor_sprite_index: 46
    wall_sprite_index: 35
    width: 80
    height: 50
    z_level: 0.0
items_settings: 
    winitem_sprite_index: 124
    winitem_name: "Cake of Destiny"
    z_level: 1.0
player_settings: {
    sprite_index: 64,
    name: "Cake Addict",
    max_health: 10,
    fov_radius: 10,
}

