
tile_size: 32
max_fov: 15
end_level: 3
entity_z_level: 1.0
npcs_settings:
    npcs: [
        {
            actor: {
                entity: {
                    sprite_index: 69,
                    name: "NPC Yoga Bunny",
                    levels: [0, 1, 2],
                    base_damage: 2,
                },
                max_health: 1,
                fov_radius: 6,
            },
            proportion: 50,
            quest: {
                name: "Get Weapon",
                item_type: Weapon,
                reward:  {
                    entity: {
                        sprite_index: 33,
                        name: "Reward Fries",
                        levels: [],
                    },
                    item_type: Healing,
                    proportion: 50,
                    effect_amount: 10,
                },
            }
        },
    ]
monsters_settings: 
    monsters: [
        {
            actor: {
                entity: {
                    sprite_index: 111,
                    name: "Nutritionist",
                    levels: [1, 2],
                    base_damage: 2,
                },
                max_health: 2,
                fov_radius: 6,
            },
            behaviour: Chasing,
            proportion: 10,
        },
        {
            actor: {
                entity: {
                    sprite_index: 79,
                    name: "Gym Bro",
                    levels: [2],
                    base_damage: 4,
                },
                max_health: 4,
                fov_radius: 6,
            },
            behaviour: Chasing,
            proportion: 30,
        },
        {
            actor: {
                entity: {
                    sprite_index: 103,
                    name: "Supplement Pusher",
                    levels: [1, 2],
                    base_damage: 3,
                },
                max_health: 3,
                fov_radius: 10,
            },
            behaviour: Chasing,
            proportion: 10,
        },
    ]
map_settings: 
    tile_sprites: {
        Floor: 46,
        Wall: 35,
        Exit: 62,
    }
    width: 80
    height: 50
    z_level: 0.0
    architect: {
        architect: Drunkard,
        num_monsters: 50,
        num_items: 30,
        num_npcs: 10,
        entity_distance: 10.0,
    }
items_settings: 
    winitem: {
        sprite_index: 124,
        name: "Cake of Destiny",
        levels: [2],
    }
    items: [
        {
            entity: {
                sprite_index: 33,
                name: "Fries",
                levels: [0, 1, 2],
            },
            item_type: Healing,
            proportion: 50,
            effect_amount: 4,
        },
        {
            entity: {
                sprite_index: 33,
                name: "Chips",
                levels: [1, 2],
            },
            item_type: Healing,
            proportion: 30,
            effect_amount: 10,
        },
        {
            entity: {
                sprite_index: 123,
                name: "Deep Fried Fish",
                levels: [1],
            },
            item_type: DungeonMap,
            proportion: 10,
        },
        {
            entity: {
                sprite_index: 115,
                name: "Rusty Sword",
                levels: [0, 1, 2, 3],
                base_damage: 2,
            },
            item_type: Weapon,
            proportion: 10,
        },
        {
            entity: {
                sprite_index: 83,
                name: "Shiny Sword",
                levels: [0, 1, 2, 3],
                base_damage: 3,
            },
            item_type: Weapon,
            proportion: 10,
        },
        {
            entity: {
                sprite_index: 47,
                name: "Super Sword",
                levels: [1, 2, 3],
                base_damage: 4,
            },
            item_type: Weapon,
            proportion: 10,
        },
    ]
player_settings: {
    entity: {
        sprite_index: 64,
        name: "Cake Addict",
        levels: [1, 2],
        base_damage: 1,
    },
    max_health: 10,
    fov_radius: 10,
}

