
tile_size: 32
max_fov: 15
monsters_settings: 
    amount: 50
    z_level: 1
    monsters: [
        {
            actor: {
                entity: {
                    sprite_index: 69,
                    name: "Yoga Bunny",
                },
                max_health: 1,
                fov_radius: 6,
            },
            behaviour: Random,
            proportion: 50,
        },
        {
            actor: {
                entity: {
                    sprite_index: 111,
                    name: "Nutritionist",
                },
                max_health: 2,
                fov_radius: 6,
            },
            behaviour: Chasing,
            proportion: 10,
        },
        {
            actor: {
                entity: {
                    sprite_index: 79,
                    name: "Gym Bro",
                },
                max_health: 4,
                fov_radius: 6,
            },
            behaviour: Chasing,
            proportion: 30,
        },
        {
            actor: {
                entity: {
                    sprite_index: 103,
                    name: "Supplement Pusher",
                },
                max_health: 3,
                fov_radius: 10,
            },
            behaviour: Chasing,
            proportion: 10,
        },
    ]
map_settings: 
    floor_sprite_index: 46
    wall_sprite_index: 35
    width: 80
    height: 50
    z_level: 0.0
    architect: Drunkard
items_settings: 
    winitem: {
        sprite_index: 124,
        name: "Cake of Destiny",
    }
    items: [
        {
            entity: {
                sprite_index: 33,
                name: "Fries",
            },
            item_type: Healing,
            proportion: 80,
        },
        {
            entity: {
                sprite_index: 123,
                name: "Deep Fried Fish",
            },
            item_type: DungeonMap,
            proportion: 20,
        },
    ]
    z_level: 1.0
    amount: 20
player_settings: {
    entity: {
        sprite_index: 64,
        name: "Cake Addict",
    },
    max_health: 10,
    fov_radius: 10,
}

